### ISSUE TITLE
Controller ReturnType 에 대하여.

### ISSUE THREAD

**Issue by xonic789** [devSeok/dev-meeting-study#56]
현재 2021.09.01 
`MessageApiController` 메서드에서, `ResponseEntity` 타입으로 리턴하였으나, `ApiResponseDto` 타입으로 리턴하는 코드로 바꿔 작성함.
![image](https://user-images.githubusercontent.com/64122884/131531290-1c2c4b46-cfa1-4a60-a718-7df1295b45d1.png)

-> 테스트 코드에서 `HttpStatusCode` 가 `201`에서 `200`으로 변경됨.

-> Http Status Code 변경하는 코드 작성 필요.

**Comment by devSeok** [comment]
ApiResponseDto에서 ResponseEntity 를 상속으로 처리후 다시 한번 회의

**Comment by xonic789** [comment]
ResponseEntity를 사용하기로 결정.
